import type { AppData } from "./types";

const now = new Date().toISOString();
const yesterday = new Date(Date.now() - 86400000).toISOString();
const tomorrow = new Date(Date.now() + 86400000).toISOString();
const nextWeek = new Date(Date.now() + 7 * 86400000).toISOString();
const lastWeek = new Date(Date.now() - 7 * 86400000).toISOString();

export const seedData: AppData = {
  categories: [
    {
      id: "cat-1",
      name: "Elektronik",
      description: "Perangkat elektronik kantor",
      color: "#ef4444",
      createdAt: now,
    },
    {
      id: "cat-2",
      name: "Kendaraan",
      description: "Kendaraan operasional",
      color: "#3b82f6",
      createdAt: now,
    },
    {
      id: "cat-3",
      name: "Peralatan Kantor",
      description: "Meja, kursi, peralatan",
      color: "#10b981",
      createdAt: now,
    },
    {
      id: "cat-4",
      name: "Alat Produksi",
      description: "Mesin & alat produksi",
      color: "#f59e0b",
      createdAt: now,
    },
  ],
  tags: [
    { id: "tag-1", name: "Prioritas", createdAt: now },
    { id: "tag-2", name: "Baru", createdAt: now },
    { id: "tag-3", name: "Rusak Ringan", createdAt: now },
    { id: "tag-4", name: "Butuh Kalibrasi", createdAt: now },
  ],
  locations: [
    {
      id: "loc-1",
      name: "Gedung Utama",
      description: "Kantor Pusat Garuda Food",
      address: "Jl. Bintaro No.1",
      parentId: null,
      createdAt: now,
    },
    {
      id: "loc-2",
      name: "Lantai 2 - IT",
      description: "Ruang IT",
      address: "Gedung Utama Lt.2",
      parentId: "loc-1",
      createdAt: now,
    },
    {
      id: "loc-3",
      name: "Gudang A",
      description: "Gudang penyimpanan",
      address: "Area Gudang",
      parentId: null,
      createdAt: now,
    },
    {
      id: "loc-4",
      name: "Ruang Meeting Garuda",
      description: "Ruang meeting besar",
      address: "Lt.1",
      parentId: "loc-1",
      createdAt: now,
    },
  ],
  customFields: [
    {
      id: "cf-1",
      name: "Tanggal Pembelian",
      type: "date",
      required: false,
      createdAt: now,
    },
    {
      id: "cf-2",
      name: "Nomor Seri",
      type: "text",
      required: true,
      createdAt: now,
    },
    {
      id: "cf-3",
      name: "Kondisi",
      type: "option",
      required: false,
      options: ["Baik", "Cukup", "Rusak"],
      createdAt: now,
    },
    {
      id: "cf-4",
      name: "Garansi (bulan)",
      type: "number",
      required: false,
      createdAt: now,
    },
  ],
  assetModels: [
    {
      id: "mdl-1",
      name: 'MacBook Air M2 13"',
      brand: "Apple",
      modelNo: "MLY33",
      categoryId: "cat-1",
      createdAt: now,
    },
    {
      id: "mdl-2",
      name: "ThinkPad X1 Carbon",
      brand: "Lenovo",
      modelNo: "X1C-G10",
      categoryId: "cat-1",
      createdAt: now,
    },
    {
      id: "mdl-3",
      name: "Proyektor Epson",
      brand: "Epson",
      modelNo: "EB-X51",
      categoryId: "cat-1",
      createdAt: now,
    },
    {
      id: "mdl-4",
      name: "Toyota Avanza",
      brand: "Toyota",
      modelNo: "AVZ-2024",
      categoryId: "cat-2",
      createdAt: now,
    },
  ],
  custodians: [
    {
      id: "cust-1",
      name: "Budi Santoso",
      nik: "1234567890",
      department: "IT",
      email: "budi@garudafood.co.id",
      phone: "081234567890",
      createdAt: now,
    },
    {
      id: "cust-2",
      name: "Siti Aminah",
      nik: "0987654321",
      department: "Marketing",
      email: "siti@garudafood.co.id",
      phone: "081298765432",
      createdAt: now,
    },
    {
      id: "cust-3",
      name: "Joko Widodo",
      nik: "1122334455",
      department: "Produksi",
      email: "joko@garudafood.co.id",
      phone: "081233445566",
      createdAt: now,
    },
    {
      id: "cust-4",
      name: "Dewi Lestari",
      nik: "5566778899",
      department: "Finance",
      email: "dewi@garudafood.co.id",
      phone: "081212345678",
      createdAt: now,
    },
  ],
  assets: [
    {
      id: "ast-1",
      name: 'MacBook Pro 16" - IT 001',
      description: "Laptop untuk tim development",
      status: "AVAILABLE",
      categoryId: "cat-1",
      locationId: "loc-2",
      assetModelId: "mdl-1",
      custodianId: null,
      qrCode: "PIN-MBP001A",
      mainImage: "",
      value: 25000000,
      serialNumber: "SN-MBP-001",
      tagIds: ["tag-1", "tag-2"],
      customValues: {
        "cf-1": "2024-01-15",
        "cf-2": "SN-MBP-001",
        "cf-3": "Baik",
      },
      notes: [
        {
          id: "n1",
          assetId: "ast-1",
          content: "Aset baru, kondisi prima",
          type: "update",
          createdAt: now,
        },
      ],
      createdAt: lastWeek,
      updatedAt: now,
    },
    {
      id: "ast-2",
      name: "Proyektor Epson EB-X51",
      description: "Proyektor ruang meeting",
      status: "CHECKED_OUT",
      categoryId: "cat-1",
      locationId: "loc-4",
      assetModelId: "mdl-3",
      custodianId: "cust-2",
      qrCode: "PIN-PRJ002B",
      mainImage: "",
      value: 8000000,
      serialNumber: "SN-PRJ-002",
      tagIds: ["tag-1"],
      customValues: { "cf-2": "SN-PRJ-002" },
      notes: [],
      createdAt: lastWeek,
      updatedAt: now,
    },
    {
      id: "ast-3",
      name: "Toyota Avanza Operasional",
      description: "Mobil operasional pooling",
      status: "AVAILABLE",
      categoryId: "cat-2",
      locationId: "loc-3",
      assetModelId: "mdl-4",
      custodianId: null,
      qrCode: "PIN-CAR003C",
      mainImage: "",
      value: 250000000,
      serialNumber: "B1234XYZ",
      tagIds: [],
      customValues: {},
      notes: [],
      createdAt: lastWeek,
      updatedAt: now,
    },
    {
      id: "ast-4",
      name: "Meja Kerja Ergonomis",
      description: "Meja standing desk",
      status: "MAINTENANCE",
      categoryId: "cat-3",
      locationId: "loc-2",
      assetModelId: undefined,
      custodianId: null,
      qrCode: "PIN-MEJ004D",
      mainImage: "",
      value: 3500000,
      serialNumber: "SN-MEJ-004",
      tagIds: ["tag-3"],
      customValues: {},
      notes: [
        {
          id: "n2",
          assetId: "ast-4",
          content: "Kaki meja goyang, perlu servis",
          type: "maintenance",
          createdAt: now,
        },
      ],
      createdAt: lastWeek,
      updatedAt: now,
    },
    {
      id: "ast-5",
      name: "Lenovo ThinkPad X1 - Dev 02",
      description: "Laptop backup developer",
      status: "CHECKED_OUT",
      categoryId: "cat-1",
      locationId: "loc-2",
      assetModelId: "mdl-2",
      custodianId: "cust-1",
      qrCode: "PIN-TP005E",
      mainImage: "",
      value: 22000000,
      serialNumber: "SN-TP-005",
      tagIds: ["tag-2"],
      customValues: {},
      notes: [],
      createdAt: lastWeek,
      updatedAt: now,
    },
    {
      id: "ast-6",
      name: "Sound System Portable",
      description: "Untuk event luar ruangan",
      status: "AVAILABLE",
      categoryId: "cat-1",
      locationId: "loc-3",
      assetModelId: undefined,
      custodianId: null,
      qrCode: "PIN-SND006F",
      mainImage: "",
      value: 12000000,
      serialNumber: "SN-SND-006",
      tagIds: [],
      customValues: {},
      notes: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "ast-7",
      name: "Kamera DSLR Canon",
      description: "Untuk dokumentasi marketing",
      status: "AVAILABLE",
      categoryId: "cat-1",
      locationId: "loc-4",
      assetModelId: undefined,
      custodianId: null,
      qrCode: "PIN-CAM007G",
      mainImage: "",
      value: 18000000,
      serialNumber: "SN-CAM-007",
      tagIds: ["tag-1"],
      customValues: {},
      notes: [],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "ast-8",
      name: "Forklift Elektrik",
      description: "Alat angkut gudang",
      status: "RETIRED",
      categoryId: "cat-4",
      locationId: "loc-3",
      assetModelId: undefined,
      custodianId: null,
      qrCode: "PIN-FRK008H",
      mainImage: "",
      value: 150000000,
      serialNumber: "SN-FRK-008",
      tagIds: [],
      customValues: {},
      notes: [
        {
          id: "n3",
          assetId: "ast-8",
          content: "Sudah tidak layak pakai",
          type: "retired",
          createdAt: now,
        },
      ],
      createdAt: lastWeek,
      updatedAt: now,
    },
  ],
  kits: [
    {
      id: "kit-1",
      name: "Paket Presentasi Lengkap",
      description: "Laptop + Proyektor + Pointer + Tas",
      status: "AVAILABLE",
      qrCode: "KIT-001",
      assetIds: ["ast-1", "ast-2"],
      categoryId: "cat-1",
      locationId: "loc-4",
      image: "",
      createdAt: now,
    },
    {
      id: "kit-2",
      name: "Paket Meeting Outdoor",
      description: "Sound + Kamera + Meja lipat",
      status: "AVAILABLE",
      qrCode: "KIT-002",
      assetIds: ["ast-6", "ast-7"],
      categoryId: "cat-1",
      locationId: "loc-3",
      image: "",
      createdAt: now,
    },
  ],
  bookings: [
    {
      id: "bk-1",
      name: "Peminjaman Proyektor Marketing",
      description: "Untuk presentasi klien",
      status: "ONGOING",
      custodianId: "cust-2",
      fromDate: yesterday,
      toDate: tomorrow,
      assetIds: ["ast-2"],
      kitIds: [],
      createdBy: "adminsystem",
      createdAt: yesterday,
      history: [
        { status: "DRAFT", at: yesterday, by: "adminsystem" },
        { status: "ONGOING", at: yesterday, by: "adminsystem" },
      ],
    },
    {
      id: "bk-2",
      name: "Peminjaman Laptop IT",
      description: "Untuk project migrasi",
      status: "OVERDUE",
      custodianId: "cust-1",
      fromDate: lastWeek,
      toDate: yesterday,
      assetIds: ["ast-5"],
      kitIds: [],
      createdBy: "adminsystem",
      createdAt: lastWeek,
      history: [
        { status: "DRAFT", at: lastWeek, by: "adminsystem" },
        { status: "ONGOING", at: lastWeek, by: "adminsystem" },
        { status: "OVERDUE", at: yesterday, by: "system" },
      ],
    },
    {
      id: "bk-3",
      name: "Booking Paket Presentasi",
      description: "Rapat direksi minggu depan",
      status: "RESERVED",
      custodianId: "cust-3",
      fromDate: tomorrow,
      toDate: nextWeek,
      assetIds: ["ast-1"],
      kitIds: ["kit-1"],
      createdBy: "adminsystem",
      createdAt: now,
      history: [{ status: "RESERVED", at: now, by: "adminsystem" }],
    },
    {
      id: "bk-4",
      name: "Peminjaman Selesai - Sound",
      description: "Event selesai",
      status: "COMPLETE",
      custodianId: "cust-4",
      fromDate: lastWeek,
      toDate: yesterday,
      actualReturnDate: now,
      returnCondition: "Baik, lengkap",
      assetIds: ["ast-6"],
      kitIds: [],
      createdBy: "adminsystem",
      createdAt: lastWeek,
      history: [
        { status: "ONGOING", at: lastWeek, by: "adminsystem" },
        { status: "COMPLETE", at: now, by: "adminsystem" },
      ],
    },
  ],
  audits: [
    {
      id: "aud-1",
      name: "Audit Q1 - Gudang A",
      status: "OPEN",
      createdBy: "adminsystem",
      createdAt: now,
      items: [
        {
          id: "ai-1",
          auditId: "aud-1",
          assetId: "ast-3",
          result: "FOUND",
          note: "Ada, kondisi baik",
          scannedAt: now,
        },
        { id: "ai-2", auditId: "aud-1", assetId: "ast-6", result: null },
        {
          id: "ai-3",
          auditId: "aud-1",
          assetId: "ast-8",
          result: "MISSING",
          note: "Tidak ditemukan di lokasi",
          scannedAt: now,
        },
      ],
    },
    {
      id: "aud-2",
      name: "Audit IT - Lantai 2",
      status: "COMPLETED",
      createdBy: "adminsystem",
      createdAt: yesterday,
      items: [
        {
          id: "ai-4",
          auditId: "aud-2",
          assetId: "ast-1",
          result: "FOUND",
          scannedAt: yesterday,
        },
        {
          id: "ai-5",
          auditId: "aud-2",
          assetId: "ast-5",
          result: "FOUND",
          scannedAt: yesterday,
        },
      ],
    },
  ],
};
